### ISSUE TITLE
mdcMenu demo: menu can't be opened after being closed by clicking disabled item

### ISSUE THREAD

**Issue by jorgevargas1989** [src-zone/material#87]
The mdcMenu closes when you click on a disabled menu item. After that you can't open it again. To reproduce:

1. Go to the mdcMenu demo: http://localhost:8090/material/components/menu
2. Click on the "Reveal" button
3. Click on the "Forward" menu item (that's a disabled menu item). Still the menu is closed
4. Click on the "Reveal" button. The menu doesn't open. I would expect it to open again.

**Comment by gjdev** [comment]
This is caused by MDC bug material-components/material-components-web#1495. We rely on notifyCancel/notifySelected to be called when the menu closes, but this is not happening consistently. I will have a look if we can workaround this in some way, as the upstream bug doesn't seem to get any love ;-).
